<?php

/**
 * Impelementation of hook_menu.
 */
function admin_utils_menu() {
  $items = array();
  $items['admin_utils/my_ip'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'admin_utils_ip_address',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  $items['admin_utils/headers'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'admin_utils_headers',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  $items['admin_utils/poll_votes'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'admin_utils_poll_votes',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  $items['admin_utils/poll_votes/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'admin_utils_poll_votes',
    'page arguments' => array(2),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  return $items;
}

function admin_utils_theme($existing, $type, $theme, $path) {
  return array(
    // Poll daddy.
    'admin_utils_ip_info' => array(
      'template' => 'ip-info',
    )
  );
}

function admin_utils_preprocess_admin_utils_ip_info(&$variables) {
  $test = null;
}

function admin_utils_ip_address() {

/* Returns the IP address of the client machine.
If Drupal is behind a reverse proxy, we use the X-Forwarded-For header
instead of $_SERVER['REMOTE_ADDR'], which would be the IP address of
the proxy server, and not the client's. The actual header name can be
configured by the reverse_proxy_header variable.
 */
  print theme('admin_utils_ip_info');
}

/**
 * Returns how many polls have been voted a specific IP address.
 * By default returns the results for the current IP.
 */
function admin_utils_poll_votes($ip = '') {

  print '<h1>poll votes utility</h1>'. PHP_EOL;

  if(empty($ip)) {
    $ip = ip_address();
  }

  print '<h4>Your current IP addres, <i>as seen by Drupal</i> is</h4>'. PHP_EOL;
  print $ip. PHP_EOL;

  print '<h4>How many times has this IP voted?</h4>
      <p>A simplified version of the following query is conducted by Drupal core polls to<br />
      determine if you are eligible to vote or not.</p>'. PHP_EOL;

  $query = "
SELECT
	pv.nid as poll_nid,
	pv.hostname,
	pv.uid,
	pv.timestamp,
	FROM_UNIXTIME(pv.timestamp - 14400, GET_FORMAT(DATETIME,'USA')) as voted_on,
	SUBSTRING(pn.title, 1, 25) as poll_title,
	an.title as article_title,
	an.nid as article_nid
FROM poll_vote pv
INNER JOIN node pn ON pv.nid = pn.nid
INNER JOIN field_data_field_article_poll poll_field ON pv.nid = poll_field.field_article_poll_nid
INNER JOIN node an ON poll_field.entity_id = an.nid
	WHERE pv.hostname=:ip
	ORDER BY pv.timestamp desc";

  $results = db_query($query, array('ip' => $ip));

  if($results) {
    print '// Query string: '. PHP_EOL;
    print preg_replace(array('/\t/', '/\n/', '/:ip/'), array('&nbsp;&nbsp;&nbsp;&nbsp;', '<br />', "'$ip'"), $query);

    $header = array('poll_nid', 'pv.hostname', 'pv.uid', 'pv.timestamp', 'voted_on', 'poll_title', 'article_title', 'article_nid');

    $rows = array();
    while($row = $results->fetch()) {
      $_row = array();
      foreach($row as $col => $value) {
        $_row[] = $value;
      }
      $rows[] = $_row;
    }

    print '<br /><br />';
    print '<h4>Results</h4>';
    print theme('table', array('header' => $header, 'rows' => $rows)). PHP_EOL;

    $count = db_query('select count(nid) from node where type=:type', array('type' => 'poll'))->fetchField();

    printf('<p>IP address %s has voted in %d out of %d polls.</p>', $ip, count($rows), $count);

  } else {
    print '<h4>Results</h4>';
    print 'The current IP address has not voted';
  }

}

function admin_utils_headers() {

}