<?php

/**
 * Response sent from Drupal to JQuery to determine whether the call to
 * tfkfav/ajax/del was successful.
 *
 * @var string
 */
define("TFK_FAVS_AJAX_SUCCESS", "success");

function tfk_favorites_menu(){
  $items['tfkfav/ajax/del'] = array(
    'title' => 'Around The World Page',
    'page callback' => '_tfk_fav_del',
    'access callback' => 'user_access',
    'access arguments' => array('access content')
  );
  return $items;
}


function tfk_favorites_block_info() {
  $blocks['tfk-favorites-links'] = array(
    'info' => t('Favorites Block')
  );
  $blocks['tfk_favorites_links'] = array(
    'info' => t('Hookable Favorites Block')
  );
  return $blocks;
}


function tfk_favorites_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'tfk-favorites-links':
      $block['subject'] = t('Favorites Block');
      $block['content'] = _tfk_favorites_links_block_content();
      break;
    case 'tfk_favorites_links':
      $block['content'] = _tfk_favorites_links_block_content();
    break;
  }

  return $block;
}

/**
 * Callback for tfk_favorites_block_view(), delta "tfk_favorites_links".
 *
 * @see tfk_favorites_block_view()
 */
function _tfk_favorites_links_block_content() {

  $ref = arg(0);
  
  $favorites_module_path = drupal_get_path('module', 'tfk_favorites');
  $search_module_path = drupal_get_path('module', 'tfk_search');
  
  // Add JS settings and file. These are used for the clear all favorites Javascript.
  drupal_add_js(array('tfk_favorites' => array('ajax_callback' => url('tfkfav/ajax/del'), 'ref' => $ref, 'success' => TFK_FAVS_AJAX_SUCCESS)), 'setting');
  drupal_add_js($favorites_module_path. '/js/tfk_favorites.js', 'file');

  // View all my favorites link.
  $link_options = array('html' => TRUE, 'attributes' => array('title' => 'All Teacher Resources'));
  $view_all = l(theme('image', array('path' => $search_module_path. '/images/all-teacher-resources.png', 'alt' => 'All Teacher Resources', 'attributes' => array('title' => 'All Teacher Resources'))), 'my-favorites', $link_options);
  
  // Clear favorites link.
  $link_options['attributes']['fragment'] = ' '; // Adds the # at the end of the link.
  $link_options['attributes'] = array('title' => 'Clear All Favorites', 'id' => 'delfavs');
  $clear_all = l(theme('image', array('path' => $search_module_path. '/images/clear-all-favorites.png', 'alt' => 'Clear All Favorites', 'attributes' => array('title' => 'Clear All Favorites'))), $ref, $link_options);
  
  // Theme output.
  $variables = array('ref' => $ref, 'view_all' => $view_all, 'clear_all' => $clear_all);
  return theme('tfk_favorites_links', $variables);
}

function tfk_favorites_theme(){
  return array(
    'tfk_favorites_links' => array(
      'template' => 'tfk-favorites-links',
      'variables' => array('list' => NULL),
    )
  );
}

/**
 * AJAX callback for deleting all user favorites.
 *
 * @see tfk_favorites_menu()
 */
function _tfk_fav_del(){
  global $user;
  $flag = flag_get_flag('favorites');

  $fid = $flag->fid;
  $res = db_query('select content_id from flag_content where fid = :fid and uid = :uid', array('fid' => $fid, 'uid' => $user->uid));
  foreach ($res as $k => $record) {
    $nid = $record->content_id;
    $flag->flag('unflag', $nid, $user);
  }

  print TFK_FAVS_AJAX_SUCCESS;
}

/**
 * Implementation of hook_preprocess_view_view_fields.
 *
 * @param array $variables
 *   Stuff comming from views.
 */
//function tfk_favorites_preprocess_views_view_fields(&$variables, $hook) {
//  $view = $variables['view'];
//  if($view->name == 'user_favorites' && $view->current_display == 'page') {
//  }
//}

/**
 * Preprocess Views list.
 */
function tfk_favorites_preprocess_views_view_list(&$variables, $hook) {
  // Add element id to ordered list. Views only allows classes.
  $variables['list_type_prefix'] = '<ol id="tfk-search-results-photos-video" class="search-results">';
}


//function tfk_favorites_preprocess_views_view(&$variables, $hook) {
//  $view = $variables['view'];
//  if($view->name == 'user_favorites' && $view->current_display == 'page') {
//  }
//}

/**
 * Implementation of hook_preprocess_page.
 */
function tfk_favorites_preprocess_page(&$variables, $hook) {
  $test = null;
  if(arg(0) == 'my-favorites') {
    $variables['section_title'] = 'MY FAVORITES';

    // Since the My Favorites page uses so many styles that are already defined in Photos and Videos, we recyle tfk_search.css.
    drupal_add_css(drupal_get_path('module', 'tfk_search'). '/css/tfk_search.css', 'file');
    
    // We also recycle some left column block and content styles from worksheets.
    drupal_add_css(drupal_get_path('module', 'tfk_search'). '/css/tfk_worksheets.css', 'file');
    
    // Finally we inherit and override as needed from a dedicated favorites stylesheet.
    drupal_add_css(drupal_get_path('module', 'tfk_favorites'). '/css/tfk_favorites.css', 'file');
  }
}


function tfk_favorites_preprocess_node(&$variables){
  
  if(array_key_exists('node', $variables) && $variables['node']->type == 'store') {

      //we dont want title to be displayeed
      $variables['title'] = '';
      $store_items = array();
      $store_items_bottom = array();
      $store_books = array();

      $items_tmp = field_get_items('node', $variables['node'], 'field_store_items');
      foreach($items_tmp as $item){
        $item_tmp = entity_load('field_collection_item', array($item['value']));
        $link_url = $item_tmp[$item['value']]->field_store_item_link_url['und'][0]['safe_value'];
        
        if(strlen($link_url) > 0 && $link_url != 'http://'){
          $image = $item_tmp[$item['value']]->field_store_item_image['und'][0]['uri'];
          $image_url = file_create_url($image);
          $store_items[$item['value']]['link_url'] = $link_url;
          $store_items[$item['value']]['image_url'] = $image_url;
        }

      }

      $books_tmp = field_get_items('node', $variables['node'], 'field_store_books');
      foreach($books_tmp as $book_id => $book){
        $book_cover_tmp = field_get_items('node',$book['node'],'field_book_image');
        $book_cover = file_create_url($book_cover_tmp[0]['uri']);

        $book_title = $book['node']->title;

        $book_link_tmp = field_get_items('node',$book['node'],'field_book_link');
        $book_link = $book_link_tmp[0]['safe_value'];

        $book_author_tmp = field_get_items('node',$book['node'],'field_book_author');
        $book_author = $book_author_tmp[0]['safe_value'];
        
        $store_books[$book_id]['book_cover'] = $book_cover;
        $store_books[$book_id]['book_title'] = $book_title;
        $store_books[$book_id]['book_link'] = $book_link;
        $store_books[$book_id]['book_author'] = $book_author;

      }


      $items_tmp = field_get_items('node', $variables['node'], 'field_store_items_bottom');
      foreach($items_tmp as $item){

        $item_tmp = entity_load('field_collection_item', array($item['value']));
        $link_url = $item_tmp[$item['value']]->field_item_url['und'][0]['safe_value'];
        if(strlen($link_url) > 0 && $link_url != 'http://'){
          $image = $item_tmp[$item['value']]->field_item_image['und'][0]['uri'];
          $image_url = file_create_url($image);

          $store_items_bottom[$item['value']]['link_url'] = $link_url;
          $store_items_bottom[$item['value']]['image_url'] = $image_url;
        }
      }

      $variables['store_books'] = $store_books;
      $variables['store_items'] = $store_items;
      $variables['store_items_bottom'] = $store_items_bottom;

  }


}
