<?php
function tfk_search_init(){
    //print_R(apachesolr_get_enabled_facets('CGKX-19447'));
}


function tfk_search_apachesolr_update_index(&$document, $node) {
  if (isset($node->field_date)){

    $tmp_date =  field_get_items('node', $node, 'field_date');
    $date = $tmp_date[0]['value'];
    $date = date('Y', $date);
    $document->addField('sm_editorial_date_tfk', $date);
  }
}

function tfk_search_apachesolr_facets() {
  $facets['sm_editorial_date_tfk'] = array(
    'info' => t('Year of the Node'),
    'facet_field' => 'sm_editorial_date_tfk',
  );
  return $facets;
}

function tfk_search_block_info() {
  $blocks = array();
  $facets = tfk_search_apachesolr_facets();
  foreach ($facets as $delta => $facet){
    $blocks[$delta] = $facets[$delta] + array('cache' => BLOCK_CACHE_PER_PAGE,);
  }
  return $blocks;
}

function tfk_search_block_view($delta='') {
  $block = array();
  if($delta == 'sm_editorial_date_tfk'){
    $block['subject'] = t('Custom ApacheSolrFilter');

    if (apachesolr_has_searched()) {
      $response = apachesolr_static_response_cache();

      if (empty($response)) {
        return;
      }
      $query = apachesolr_current_query();
      $block['content'] = apachesolr_facet_block($response, $query, 'tfk_search', $delta, $delta, t($facet['info']));
    }else{
      $block['content'] = '';
    }
  }
  return $block;
}

function tfk_search_block_configure($delta='') {
  if($delta == 'sm_editorial_date_tfk'){
      return apachesolr_facetcount_form('sm_editorial_date_tfk', $delta);
  }
}


function tfk_search_block_save($delta = '', $edit = array()){
  if($delta == 'solr_filter_year'){
     apachesolr_facetcount_save($edit);
  }
  return;
}

?>