<?php

/**
 * Implementation of menu_hook.
 */
function tfk_page_paths_menu(){
    //flog_it("tfk_page_paths_menu");
	$items = array();

        $items['store'] = array(
		'title' => 'TFK Store',
		'page callback' => 'tfk_store_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['magazine'] = array(
		'title' => 'TFK Magazine',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
    	$items['digital'] = array(
		'title' => 'Digital Edition',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['assessment'] = array(
		'title' => 'TFK Assessment',
		'page callback' => 'tfk_pv_page_callback',
                'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['no-assessment'] = array(
		'title' => 'TFK No Assessment Access',
		'page callback' => 'tfk_no_assessment_callback',
                'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['cognero-down'] = array(
		'title' => 'TFK Cognero Down',
		'page callback' => 'tfk_cognero_down_callback',
                'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['extras'] = array(
		'title' => 'TFK Extras',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['subscribe-renew'] = array(
		'title' => 'Subscribe & Renew',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access protected content')
	);
        $items['mini-sites'] = array(
		'title' => 'Mini-Sites',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);   
        $items['news-archive'] = array(
		'title' => 'News Archive',
		'page callback' => '_tfk_news_archive_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	); 
        $items['news-archive/%'] = array(
		'title' => 'News Archive',
		'page callback' => '_tfk_news_archive_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);  
        $items['info'] = array(
		'title' => 'Info',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['404page'] = array(
		'title' => 'Page Not Found',
		'page callback' => 'tfk_not_found_page',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['deniedpage'] = array(
		'title' => 'SUBSCRIBER-ONLY CONTENT',
		'page callback' => 'tfk_denied_page',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
	return $items;
}


function _tfk_news_archive_callback(){
    return '';
}


function tfk_page_paths_preprocess_page(&$variables){
    global $user;
    global $base_path;
    
    $args = arg();
    //flog_it("***tfk_page_paths_preprocess_page:");
    
    
    // tfk-50, tfk-34, tfk-83: Add new items to paywall
    if ( isset($args[0]) && $args[0] == "node" && isset($variables['node']) ) { 
        $node = $args[1];
        //flog_it("content_type=".$variables['node']->type);
        if ($variables['node']->type == "article" || $variables['node']->type == "slideshow" || $variables['node']->type == "video" || $variables['node']->type == "minisite") {
            $flag = flag_get_flag("magazine_cover_story");
 
            //flog_it("is_flagged=".$flag->is_flagged($node));
            if ($flag->is_flagged($node)) {
                //flog_it($node." is flagged as a Magazine article");
                
                // Check to see if this is an anonymous user: if it is -> 403
                //flog_it("anon=".$variables['is_anon']);
                
                if ($variables['is_anon']) {
                   drupal_add_http_header('Status', '403 Forbidden');
                   //flog_it("Before drupal_deliver_page...");
                   drupal_deliver_page(MENU_ACCESS_DENIED);
                   //flog_it("After drupal_deliver_page: Calling drupal_exit()...");
                   drupal_exit();
                }
            }
        }
    }
    
    // Check for the tfk-magazine path and an anonymous user
    //flog_it("args[0]=".$args[0].", is_anon=".$variables['is_anon']);
    if (strstr($args[0], "tfk-magazine") && $variables['is_anon']) {
        //flog_it("Found Anon & magazine path...");
        drupal_add_http_header('Status', '403 Forbidden');
        drupal_deliver_page(MENU_ACCESS_DENIED);
        drupal_exit();
    }
    
    // Check for the digital editions path and an anonymous user
    if (strstr($args[0], "digital") && $variables['is_anon']) {
        //flog_it("Found Anon & digital editon path...");
        drupal_deliver_page(MENU_ACCESS_DENIED);
        drupal_exit();
    }
    
    // Check for the assessment path and an anonymous user
    if (strstr($args[0], "assessment") && $variables['is_anon']) {
        //flog_it("Found Anon & assessment path...");
        drupal_deliver_page(MENU_ACCESS_DENIED);
        drupal_exit();
    }
    
    if($args[0] == 'deniedpage'){
        $variables['section_title'] = 'SUBSCRIBER-ONLY CONTENT';
    }
    
    // Check to add (nid) to the admin/content page
    if(isset($variables['page']['content']['system_main']['admin']['nodes'])){
        foreach($variables['page']['content']['system_main']['admin']['nodes']['#options'] as $nid_id =>$node_item){
            $variables['page']['content']['system_main']['admin']['nodes']['#options'][$nid_id]['title']['data']['#title'] = $variables['page']['content']['system_main']['admin']['nodes']['#options'][$nid_id]['title']['data']['#title'].' (id:'.$nid_id.')';
            //flog_it("nid_id=".$nid_id.", node_item=".$node_item);
            
        }
    
    }
    
    // Check for TFK Assessment processing
    if ($args[0] == 'no-assessment' || $args[0] == 'cognero-down') {
        //flog_it($variables);
        //$variables['page']['header'] = '';
        $variables['page']['sidebar_second'] = '';
        //$variables['page']['footer'] = '';
        //tfk_assessment_callback(); 
    }
}

function tfk_assessment_access_callback() {
    //flog_it("tfk_assessment_access_callback: user_is_anonymous: ".  user_is_anonymous());
    if (user_is_anonymous()) {
        return false;
    }
    return true;
}

function tfk_no_assessment_callback() {
    //flog_it("tfk_no_assessment_callback...");
  
    return theme('tfk_no_assessment');
}

function tfk_cognero_down_callback() {
    //flog_it("tfk_cognero_down_callback...");
  
    return theme('tfk_cognero_down');
}


function tfk_not_found_page(){
  return theme('tfk_not_found_page');
}

function tfk_denied_page(){
    return theme('tfk_denied_page');
}

function tfk_page_paths_theme() {
  //flog_it("tfk_page_paths_theme...");
  return array(
    'tfk_not_found_page' => array(
      'template' => 'tfk-not-found-page',
      'variables' => array('list' => NULL),
    ),
    'tfk_denied_page' => array(
      'template' => 'tfk-denied-page',
      'variables' => array('list' => NULL),
    ),
    'tfk_no_assessment' => array(
      'template' => 'tfk-no-assessment',
      'variables' => array('list' => NULL),
    ),
    'tfk_cognero_down' => array(
      'template' => 'tfk-cognero-down',
      'variables' => array('list' => NULL),
    )
  );
}




function tfk_page_paths_permission() {
  //flog_it("tfk_page_paths_permission");
  return array(
    'access protected content' => array(
      'title' => t('TFK Custom Permission'),
      'description' => t('TFK Custom Permission'),
    ),
    'view anonymous board member' => array(
      'title' => t('TFK View Anonymous Board Member'),
      'description' => t('TFK View Anonymous Board Member'),
    )
  );
}

function tfk_store_callback(){
  return '';
  //return drupal_set_title('TFK Store');
}





function tfk_pv_page_callback() {
    //flog_it("tfk_pv_page_callback...");
    return '';
}



//$args = arg();
//if(isset($args[1]) && !is_numeric($args[1])){
//return $args[1];
//}elseif(isset($args[1]) && is_numeric($args[1])){
//    return $args[1];
//}else{
//    return 'all';
//}
