<?php

/**
 * @file
 * Helper module for Time Inc. sites.
 */

/**
 * Error code issued by Drupal when a file is not found.
 *
 * @var int
 */
define('E_FILE_NOT_FOUND', 1025);

/**
 * Check that the file exists.
 *
 * @param $file
 *   A Drupal file object.
 *
 * @return
 *   An array. If the file does not exist, it will contain the E_FILE_NOT_FOUND
 *   constant.
 *
 * @see hook_file_validate()
 */
function timeinc_helper_file_exists(stdClass $file) {
  if(property_exists($file, 'abspath')) {
    if(!file_exists($file->abspath)) {
      return array(E_FILE_NOT_FOUND);
    }
  } else {
    $abspath = file_create_url($file->uri);
    if(!file_exists($abspath)) {
      return array(E_FILE_NOT_FOUND);
    }
  }
}