<?php
/**
 * @file
 * Code for the TFK Slideshow feature.
 */

include_once('feature_slideshow.features.inc');

/**
 * Preprocessor for page.
 *
 * @param array $vars
 */
function feature_slideshow_preprocess_page(&$vars) {
  // Add Slideshow page CSS.
  if(arg(0) == 'node' && array_key_exists('node', $vars) && ($vars['node']->type == 'slideshow') ) {
    drupal_add_css(drupal_get_path('module', 'feature_slideshow'). '/css/feature_slideshow.css', 'file');
  }
}

