<?php
/**
 * @file
 * tfk_local_solr.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function tfk_local_solr_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-0V61fyJ8a8J9pooEiSX0qrxxb63Wq6OJ'] = array(
    'cache' => '-1',
    'css_class' => '',
    'custom' => '0',
    'delta' => '0V61fyJ8a8J9pooEiSX0qrxxb63Wq6OJ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'tfk' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tfk',
        'weight' => '0',
      ),
    ),
    'title' => 'Grade Level',
    'visibility' => '0',
  );

  $export['facetapi-1vx93wKyU7HoAzs6sa0PMm14kMgfBQ1d'] = array(
    'cache' => '-1',
    'css_class' => '',
    'custom' => '0',
    'delta' => '1vx93wKyU7HoAzs6sa0PMm14kMgfBQ1d',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'tfk' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tfk',
        'weight' => '0',
      ),
    ),
    'title' => 'Select a Date Range',
    'visibility' => '0',
  );

  $export['facetapi-4mPrBk5hDm1iI5sCraXsbQ0GyCdhQshz'] = array(
    'cache' => '-1',
    'css_class' => '',
    'custom' => '0',
    'delta' => '4mPrBk5hDm1iI5sCraXsbQ0GyCdhQshz',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'tfk' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tfk',
        'weight' => '0',
      ),
    ),
    'title' => 'Categories',
    'visibility' => '0',
  );

  $export['facetapi-GiIy4zr9Gu0ZSa0bumw1Y9qIIpIDf1wu'] = array(
    'cache' => '-1',
    'css_class' => '',
    'custom' => '0',
    'delta' => 'GiIy4zr9Gu0ZSa0bumw1Y9qIIpIDf1wu',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'tfk' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tfk',
        'weight' => '0',
      ),
    ),
    'title' => 'Content Types',
    'visibility' => '0',
  );

  $export['facetapi-MP76BI8r9G3Ss3ujzRLzut4J9ApVXxLG'] = array(
    'cache' => '-1',
    'css_class' => '',
    'custom' => '0',
    'delta' => 'MP76BI8r9G3Ss3ujzRLzut4J9ApVXxLG',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'tfk' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tfk',
        'weight' => '0',
      ),
    ),
    'title' => 'Skills',
    'visibility' => '0',
  );

  $export['facetapi-VIxnsypWMyIDU3x6J0Ky3ArmXNSrcCls'] = array(
    'cache' => '-1',
    'css_class' => '',
    'custom' => '0',
    'delta' => 'VIxnsypWMyIDU3x6J0Ky3ArmXNSrcCls',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'tfk' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tfk',
        'weight' => '0',
      ),
    ),
    'title' => 'Themes',
    'visibility' => '0',
  );

  return $export;
}
