<?php
function tfk_store_init() {
  //Add JS include based on url
  $destination = drupal_get_destination();
  $destination = preg_replace('/\?.*/', '', $destination['destination']);
  if (drupal_lookup_path('alias',$destination) == "store/subscriptions") {
    $tfk_store_js = drupal_get_path('theme', 'tfk') .'/js/store.js';
    drupal_add_js($tfk_store_js, 'file');
  }
}
/**
 * Implementation of hook_views_pre_render()
 * 
 * check for thumbnail override image and if it's present swap it in in place
 * of the image-style generated one.
 * 
 * @param type $view
 */
function tfk_store_views_pre_render(&$view) {
    /*
     * The views and view dieplays handled here are:
     * 'books':'all_books'
     * 'other_products':'all_products'
     * 
     */
    $views = array('books','other_products');
    $displays = array('all_books','all_products');
    
    if((in_array($view->name ,$views)) && (in_array($view->current_display,$displays))) {
        foreach($view->result as $field) {
            $override = $field->field_field_thumbnail_override_image;
            if(isset($override[0]['rendered'])) {
                $override_obj = $override[0];
                $rendered_override_obj = $override_obj['rendered'];
                $rendered_override_obj_item = $rendered_override_obj['#item'];
                $rendered_override_obj_item_uri = $rendered_override_obj_item['uri'];
                if(isset($rendered_override_obj_item_uri)) {
                    if(isset($field->field_field_book_image)) { // it's a book
                        $field->field_field_book_image[0]['rendered']['#item']['uri'] = $rendered_override_obj_item_uri;
                    }
                    if(isset($field->field_field_product_image)) { // it's a product
                        $field->field_field_product_image[0]['rendered']['#item']['uri'] = $rendered_override_obj_item_uri;
                    }
                }
            }
        }
    }
}