<?php

function tfk_current_issue_block_info() {
  $blocks['current-issue-page'] = array(
    'info' => t('Global right sidebar for current magazine issue.')
  );

  return $blocks;
}

function tfk_current_issue_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'current-issue-page':
      //$block['subject'] = t('Global right sidebar for current magazine issue.');
      $block['content'] = _tfk_current_issue_block_content();
      break;
  }
  return $block;
}

function _tfk_current_issue_block_content(){
    return theme('current_issue_page',_tfk_current_issue_block_content_data());
}

function tfk_current_issue_theme() {
  return array(
    'current_issue_page' => array(
      'template' => 'current-issue-page',
      'variables' => array('list' => NULL),
    )
  );
}

function _tfk_current_issue_block_content_data(){
    global $user;    
    $uid  = $user->uid;
    $vid = 6;  
    $result = db_query('select n.title,n.nid,ti.tid,td.name,fc.field_cover_nid,fi.field_image_fid,fm.filename
        from node n left join taxonomy_index ti on n.nid = ti.nid 
        left join taxonomy_term_data td on ti.tid = td.tid
        left join field_data_field_grade_level gl on gl.field_grade_level_tid = ti.tid 
        left join field_data_field_cover fc on n.nid = fc.entity_id
        left join field_data_field_image fi on fc.field_cover_nid = fi.entity_id
        left join file_managed fm on fm.fid = fi.field_image_fid
        left join field_data_field_date fd on n.nid = fd.entity_id
        where n.type = :type and td.vid = :vid and gl.entity_type =  :entity_type and gl.entity_id = :user_id      
        order by fd.field_date_value desc LIMIT 0,1',
            array('type'=>'magazine_issue','entity_type' => 'user','user_id' => $uid,'vid' => $vid));  
    $magazine_data = array();
    foreach ($result as $k=>$record) {   
        $magazine_data[$k]['magazine_title']  = $record->title;
        $magazine_data[$k]['magazine_grade_level']  = $record->name;
        $magazine_data[$k]['magazine_path']  = drupal_lookup_path('alias','node/'.$record->nid);
        $magazine_data[$k]['magazine_cover_image']  = file_create_url(file_build_uri(basename($record->filename)));   
    }
    $list = array('magazine_data' => $magazine_data);
    return $list;
}
