<?php

//function tfk_favorites_init(){
//  if(arg(0) == 'worksheets' || arg(0) == 'photos-video'){
//    $js_path = drupal_get_path('theme', 'tfk') .'/js/atw_favorites.js';
//    drupal_add_js($js_path,'file');
//  }
//}



function tfk_favorites_menu(){
  $items['tfkfav/ajax/del'] = array(
          'title' => 'Around The World Page',
          'page callback' => '_tfk_fav_del',
          'access callback' => 'user_access',
          'access arguments' => array('access content')
  );
  return $items;
}


function tfk_favorites_block_info() {
  $blocks['tfk-favorites-links'] = array(
    'info' => t('Favorites Block')
  );
  return $blocks;
}


function tfk_favorites_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'tfk-favorites-links':
      $block['subject'] = t('Favorites Block');
      $block['content'] = _tfk_favorites_links_block_content();
      break;
  }

  return $block;
}

function _tfk_favorites_links_block_content(){

  $ref = arg(0);

  return theme('tfk_favorites_links',array('ref'=>$ref));
}

function tfk_favorites_theme(){
  return array(
    'tfk_favorites_links' => array(
      'template' => 'tfk-favorites-links',
      'variables' => array('list' => NULL),
    )
  );
}

function _tfk_fav_del(){
  global $user;
  $flag = flag_get_flag('favorites');

  $fid = $flag->fid;
  $res = db_query('select content_id from flag_content where fid = :fid and uid = :uid',array('fid'=>$fid,'uid' => $user->uid));
  foreach ($res as $k => $record) {
    $nid = $record->content_id;
    $flag->flag('unflag', $nid, $user);
  }

  echo 'success';
  exit;
  
}


function tfk_favorites_preprocess_node(&$variables){
  
  if(array_key_exists('node', $variables) && $variables['node']->type == 'store') {

     
      //we dont want title to be displayeed
      $variables['node']->title = '';
      $store_items = array();
      $store_items_bottom = array();
      $store_books = array();

      $items_tmp = field_get_items('node', $variables['node'], 'field_store_items');
      foreach($items_tmp as $item){
        $item_tmp = entity_load('field_collection_item', array($item['value']));
        $link_url = $item_tmp[$item['value']]->field_store_item_link_url['und'][0]['safe_value'];
        
        if(strlen($link_url) > 0 && $link_url != 'http://'){
          $image = $item_tmp[$item['value']]->field_store_item_image['und'][0]['uri'];
          $image_url = file_create_url($image);
          $store_items[$item['value']]['link_url'] = $link_url;
          $store_items[$item['value']]['image_url'] = $image_url;
        }

      }

      $books_tmp = field_get_items('node', $variables['node'], 'field_store_books');
      foreach($books_tmp as $book_id => $book){
        $book_cover_tmp = field_get_items('node',$book['node'],'field_book_image');
        $book_cover = file_create_url($book_cover_tmp[0]['uri']);

        $book_title = $book['node']->title;

        $book_link_tmp = field_get_items('node',$book['node'],'field_book_link');
        $book_link = $book_link_tmp[0]['safe_value'];

        $book_author_tmp = field_get_items('node',$book['node'],'field_book_author');
        $book_author = $book_author_tmp[0]['safe_value'];
        
        $store_books[$book_id]['book_cover'] = $book_cover;
        $store_books[$book_id]['book_title'] = $book_title;
        $store_books[$book_id]['book_link'] = $book_link;
        $store_books[$book_id]['book_author'] = $book_author;

      }


      $items_tmp = field_get_items('node', $variables['node'], 'field_store_items_bottom');
      foreach($items_tmp as $item){

        $item_tmp = entity_load('field_collection_item', array($item['value']));
        $link_url = $item_tmp[$item['value']]->field_item_url['und'][0]['safe_value'];
        if(strlen($link_url) > 0 && $link_url != 'http://'){
          $image = $item_tmp[$item['value']]->field_item_image['und'][0]['uri'];
          $image_url = file_create_url($image);

          $store_items_bottom[$item['value']]['link_url'] = $link_url;
          $store_items_bottom[$item['value']]['image_url'] = $image_url;
        }
      }


      
//
      $variables['store_books'] = $store_books;
      $variables['store_items'] = $store_items;
      $variables['store_items_bottom'] = $store_items_bottom;

  }


}
