<?php

/**
 * Implementation oh hook_node_view.
 * Enter description here ...
 * @param unknown_type $node
 * @param unknown_type $view_mode
 * @param unknown_type $langcode
 */
function timeinc_video_node_view($node, $view_mode, $langcode) {
  #$test = null;
  #drupal_add_js(drupal_get_path('theme', 'tfk'). '/js/atw_homepage_slideshow.js','file');
  #drupal_add_css(drupal_get_path('theme', 'tfk'). '/css/atw_homepage_slideshow.css', 'file');

  $node->video_url = file_create_url($node->field_video['und'][0]['uri']);
}

function timeinc_video_preprocess_node(&$vars, $hook) {
  #if($vars['node']->type == 'video' && arg(0) == 'node') {
  #  $vars['video_url'] = file_create_url($vars['field_video'][0]['uri']);
  #}
}

/**
 * Implementation of hook_block_info.
 *
 * Here we expose blocks that are usable by other modules.
 */
function timeinc_video_block_info() {
  $blocks = array();
  
  // TFK Photos and Video More Items Block.
  $blocks['timeinc_video_embed'] = array(
    'info' => t('Time Inc Video embed'),
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  
  return $blocks;
}


/**
 * Implementation of hook_block_view.
 */
function timeinc_video_block_view($delta='') {
  $block = array();
  
  switch ($delta) {
    
    // Node embed video.
    case 'timeinc_video_embed':

      
      if(arg(0) == 'node') {
        $node = node_load(arg(1));
        if($node->type == 'video') {
          
          $js_path = drupal_get_path('module', 'timeinc_video'). '/js';
          
          $container_id = '#video_embed_container';
          
          $settings = array(
          	'id' => $container_id,
          	'url' => $node->video_url,
            'swf_path' => $js_path,
          );
          drupal_add_js(array('timeinc_video' => $settings), 'setting');
          
          $options = array(
            'type' => 'file',
            'scope' => 'header',
            'group' => JS_LIBRARY
          );
          
          drupal_add_css(drupal_get_path('module', 'timeinc_video'). '/skins/blue_monday/jplayer.blue.monday.css', 'file');
          
          drupal_add_js($js_path. '/jquery.jplayer.min.js', $options);
          
          drupal_add_js($js_path. '/video_embed.js', $options);
          
          #$block['content'] = theme_jplayer_video($node->video_url, $container_id);
        }
      } else {
        $block['content'] = '';
      }
      
    break;
    
  }
  
  return $block;
}

function theme_jplayer_video($video_url, $container_id) {
  
  $output = '
  <div class="jp-video jp-video-270p">
    <div class="jp-type-single">
      <div id="jquery_jplayer_1" class="jp-jplayer"></div>
      <div id="jp_interface_1" class="jp-interface">
        <div class="jp-video-play"></div>
        <ul class="jp-controls">
          <li><a href="#" class="jp-play" tabindex="1">play</a></li>
          <li><a href="#" class="jp-pause" tabindex="1">pause</a></li>
          <li><a href="#" class="jp-stop" tabindex="1">stop</a></li>
          <li><a href="#" class="jp-mute" tabindex="1">mute</a></li>
          <li><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
        </ul>
        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>
        <div class="jp-volume-bar">
          <div class="jp-volume-bar-value"></div>
        </div>
        <div class="jp-current-time"></div>
        <div class="jp-duration"></div>
      </div>
      <div id="jp_playlist_1" class="jp-playlist">
        <ul>
          <li>Title of media</li>
        </ul>
      </div>
    </div>
  </div>';
  
  #$output = '<div style="height: 300px; background-color: black;">&nbsp';
  #$output .= '<div style="height: 300px; background-color: red;" id="'. $container_id. '"></div>';
  #$output .= '</div>';
  return $output;
}
