<?php
/**
 * Handles Ads and Omniture for TFK
 */

//JS files
function tfk_ads_omni_init(){
    /*Ads*/
    $ti_ad_library = "http://img.timeinc.net/shared/static/js/tii_ads.js";
    drupal_add_js($ti_ad_library,'external');
    /*Omniture  IN PROGRESS*/
    $tfk_omni_library = drupal_get_path('theme', 'tfk') .'/js/timekids-omniture.js';
    //drupal_add_js($tfk_omni_library,'file');
}

//Channel based logic
function tfk_ads_omni_preprocess_page(&$variables){
    /*adFactory config*/
    $ad_factory = "var adConfig = new TiiAdConfig(\"3475.tfk\");adConfig.setCmSitename(\"cm.tfk\");adConfig.setRevSciTracking(true);";
    $ad_factory .= "var adFactory = new TiiAdFactory(adConfig, \"kids/homepage\");adFactory.setChannel(\"home\");adFactory.setSubchannel(\"\");adFactory.setChannelPage();adFactory.setParam(\"ptype\", \"channel\");";
    drupal_add_js($ad_factory, 'inline');
    /*Set ad call values*/
    $variables['ad']['banner_728x90'] = tfk_ads_omni_create_ad('banner_728x90',728,90,'regular',1);
    $variables['ad']['banner_160x600'] = tfk_ads_omni_create_ad('banner_160x600',160,600,'regular');
    $variables['ad']['banner_728x90_footer'] = tfk_ads_omni_create_ad('banner_160x600',160,600,'regular',2);
}
function tfk_ads_omni_create_ad($name,$width,$height,$type='regular',$position=NULL){
    /**
     * Arguments
     * $name: Used for the div id.
     * $height: Used for adFactory.getAd
     * $width: Used for adFactory.getAd
     * $type: can be regular or cm
     * $position: Adds ad.setPosition($position) if needed
     * $zone: Override the zone if needed
     */
     if ($type == "regular") {
        $ad_tag = "<div id=\"$name\"><script type=\"text/javascript\">ad = adFactory.getAd($width, $height);".$ad_position."ad.write();</script></div>";
     } elseif ($type == "cm") {
        $ad_tag = "<div id=\"$name\"><script type=\"text/javascript\">adFactory.getCmAd($width, $height, \"global\", \"tout\").write();</script></div>";
     }
     return $ad_tag;
}