<?php

/**
 * Implementation of menu_hook.
 */
function tfk_page_paths_menu(){
	$items = array();

        $items['store'] = array(
		'title' => 'TFK Store',
		'page callback' => 'tfk_store_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['magazine'] = array(
		'title' => 'TFK Magazine',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
    	$items['digital'] = array(
		'title' => 'Digital Edition',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['digital-edition'] = array(
		'title' => 'Digital Edition',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access protected content')
	);
        $items['extras'] = array(
		'title' => 'TFK Extras',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['subscribe-renew'] = array(
		'title' => 'Subscribe & Renew',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access protected content')
	);
        $items['mini-sites'] = array(
		'title' => 'Mini-Sites',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);   
        $items['news-archive'] = array(
		'title' => 'News Archive',
		'page callback' => '_tfk_news_archive_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	); 
        $items['news-archive/%'] = array(
		'title' => 'News Archive',
		'page callback' => '_tfk_news_archive_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);  
        $items['info'] = array(
		'title' => 'Info',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['404page'] = array(
		'title' => 'Page Not Found',
		'page callback' => 'tfk_not_found_page',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['deniedpage'] = array(
		'title' => 'SUBSCRIBER-ONLY CONTENT',
		'page callback' => 'tfk_denied_page',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
	return $items;
}


function _tfk_news_archive_callback(){
    return '';
}


function tfk_page_paths_preprocess_page(&$variables){
    $args = arg();
    if($args[0] == 'deniedpage'){
        $variables['section_title'] = 'SUBSCRIBER-ONLY CONTENT';
    }
    
    if(isset($variables['page']['content']['system_main']['admin']['nodes'])){

        foreach($variables['page']['content']['system_main']['admin']['nodes']['#options'] as $nid_id =>$node_item){
            $variables['page']['content']['system_main']['admin']['nodes']['#options'][$nid_id]['title']['data']['#title'] = $variables['page']['content']['system_main']['admin']['nodes']['#options'][$nid_id]['title']['data']['#title'].' (id:'.$nid_id.')';
        }
    
    }
    
    
}


function tfk_not_found_page(){
  return theme('tfk_not_found_page');
}

function tfk_denied_page(){
    return theme('tfk_denied_page');
}

function tfk_page_paths_theme() {
  return array(
    'tfk_not_found_page' => array(
      'template' => 'tfk-not-found-page',
      'variables' => array('list' => NULL),
    ),
    'tfk_denied_page' => array(
      'template' => 'tfk-denied-page',
      'variables' => array('list' => NULL),
    )
  );
}




function tfk_page_paths_permission() {
  return array(
    'access protected content' => array(
      'title' => t('TFK Custom Permission'),
      'description' => t('TFK Custom Permission'),
    )
  );
}

function tfk_store_callback(){
  return '';
  //return drupal_set_title('TFK Store');
}





function tfk_pv_page_callback() {
	return '';
}



//$args = arg();
//if(isset($args[1]) && !is_numeric($args[1])){
//return $args[1];
//}elseif(isset($args[1]) && is_numeric($args[1])){
//    return $args[1];
//}else{
//    return 'all';
//}