<?php

/************************************
** Pre-Process Functions 
************************************/

/* Pre-Process Node */
function tfk_preprocess_node(&$variables) {
	/* switch based on content type */
	switch ($variables['type'])
	{
		case "slideshow":
			$variables['display_submitted'] = false; 
		break;
	}	

}

/************************************
** Slideshow - Images 
************************************/


?>
