<?php

function tfk_page_paths_menu(){
	$items = array();
	$items['photos-video'] = array(
		'title' => 'Photos & Video',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['magazine'] = array(
		'title' => 'TFK Magazine',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['worksheets'] = array(
		'title' => 'Worksheets',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
        $items['digital-edition'] = array(
		'title' => 'Digital Edition',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);          
        $items['extras'] = array(
		'title' => 'TFK Extras',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	); 
        $items['subscribe-renew'] = array(
		'title' => 'Subscribe & Renew',
		'page callback' => 'tfk_pv_page_callback',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);           
	return $items;
}

function tfk_pv_page_callback() {
	return '';
}