<?php

function tfk_user_profile_form_user_login_alter( &$form, $form_state ){
    $form['#validate'] = array(  'user_login_name_validate','user_login_authenticate_validate', 'tfk_user_profile_login_validate', 'user_login_final_validate' );
}


function tfk_user_profile_login_validate( $form, &$form_state ){
    $username = $form_state['values']['name'];
    $response = lucie_check_user($username, $form_state['values']['pass'] );
    if ($response != false)
    {
        user_external_login_register( $username, 'project_authentication' );
        $account = user_external_load($username);
        $form_state['uid'] = $account->uid;
    }
}


function lucie_check_user($email,$password){
  $url = 'http://cgi.timeinc.com/webservices/customers/'.check_plain($email).'/SI/auth_token';
  $pass_arr = array('password'=>$password);
  $pass = drupal_json_encode($pass_arr);

  $response = drupal_http_request($url,
          array('headers' => array('Content-Type'=>'application/json'),
              'method'=> 'POST',
              'data' => $pass
              ));
  if($response->code == 201){
    return true;
  }else{
    return false;
  }
}