<?php


/**
 * Photos and Video menu callback.
 */
function timeinc_search_photos_and_video() {

    module_load_include('module', 'search');
  
    $filterstring = isset($_GET['filters']) ? $_GET['filters'] : '';
    $solrsort = isset($_GET['solrsort']) ? $_GET['solrsort'] : '';
    $page = isset($_GET['page']) ? $_GET['page'] : 0;
    $base_path = 'photos-video';
    
    $response = apachesolr_search_run(search_get_keys(), $filterstring, $solrsort, $base_path, $page, 'apachesolr_search');

    return theme('search_results', array('results' => $response));
    
	return '';
}

/**
 *
 * Enter description here ...
 * @param unknown_type $variables
 */
function timeinc_search_preprocess_search_results(&$variables) {
  // If this is a solr search, expose more data to themes to play with.
  if ($variables['module'] == 'apachesolr_search') {
    $variables['response'] = apachesolr_static_response_cache();
    if (empty($variables['response'])) {
      $variables['description'] = '';
      return;
    }
    $variables['query'] = apachesolr_current_query();
    $total = $variables['response']->response->numFound;
    $params = $variables['query']->params;

    $variables['description'] = t('Showing items @start through @end of @total.', array(
      '@start' => $params['start'] + 1,
      '@end' => $params['start'] + $params['rows'] - 1,
      '@total' => $total,
    ));
  }
}

/**
 * Implementation of hook_apachesolr_modify_query().
 *
 * Limit the search results to image and video content type.
 */
function timeinc_search_apachesolr_modify_query(&$query, $caller) {
  
  // Only apply these filters when we are in the photos and video page.
  if($query->get_base_path() === 'photos-video') {
    $subquery = apachesolr_drupal_query();
    $subquery->add_filter('bundle', 'image');
    $subquery->add_filter('bundle', 'slideshow');
    $query->add_subquery($subquery, 'OR');
  }
   
}


