<?php

/*
 * Implementation of hook_menu
 */
function homework_menu() {

	$items['homework'] = array(
		'title' => 'List of homeworks',
		'page callback' => 'homework_list',
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
	
	$items['homework/add'] = array(
		'title' => 'Add homework',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('homework_form'),
		'access callback' => 'user_access',
		'access arguments' => array('access content')
	);
	
	$items['homework/%/edit'] = array(
	
	);
	
	$items['homework/%/delete'] = array(
	
	);
	
	return $items;
}

function homework_list() {
	
	$content = l(t('Add homework'), 'homework/add');
	
	$result = db_query('select * from {homework}');
	while ($obj = $result->fetchObject()) {
		$rows[] = array (check_plain($obj->title), $obj->grade_level, '');
	}
	
	$header = array(t('Title'), t('Grade Level'), t('Actions'));
	
	$content .= theme ('table' , array ('header' => $header, 'rows' => $rows));
	
	return $content;

}

function homework_form($form, &$form_state) {

	$form['title'] = array(
		'#type' => 'textfield',
		'#title' => t('Title'),
		'#required' => TRUE
	);
	
	$form['grade_level'] = array(
		'#type' => 'select',
		'#title' => t('Grade Level'),
		'#options' => array('k1' => 'K1', 'k2' => 'K2', 'k3' => 'K3')
	);
	
	$form['description'] = array(
		'#type' => 'textarea',
		'#title' => t('Description'),
	);
	
	$form['save'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);
	
	return $form;
}

function homework_form_submit($form, &$form_state) {

	if($form_state['values']['op'] == t('Save')) {
	
		$homework = new stdClass();
		$homework->title = $form_state['values']['title'];
		$homework->grade_level = $form_state['values']['grade_level'];
		$homework->description = $form_state['values']['description'];
		
		drupal_write_record('homework', $homework);
		drupal_set_message(t('Thanks mate!'));
		drupal_goto('homework');
	}
}