<?php

/**
 * @file
 * A multistep form for interactive Grammar Wizard quizzes.
 */

/**
 * Implements hook_node_view().
 */
function grammar_wizard_node_view($node, $view_mode) {
  if ($node->type == 'grammar_practice' && $view_mode == 'full') {
    $node->content['grammar_wizard'] = drupal_get_form('grammar_wizard_multistep_form', $node);
  }
}

/**
 * A multistep form, where a different and sequential form
 * is presented on each step of the form.
 *
 * In the AJAX version, the form is replaced for each wizard section. In the
 * multistep version, it causes a new page load.
 *
 * @param $form
 * @param $form_state
 */
function grammar_wizard_multistep_form($form, &$form_state, $node) {
  module_load_include('inc', 'grammar_wizard', 'grammar_wizard.pages');

  // Provide a wrapper around the entire form, since we'll replace the whole
  // thing with each submit.
  $form['#prefix'] = '<div id="wizard-form-wrapper">';
  $form['#suffix'] = '</div>';
  $form['#tree'] = TRUE; // We want to deal with hierarchical form values.

  // Make sure the form is cached so data is stored between page loads.
  $form_state['cache'] = TRUE;
  // The questions should be cached, so that they aren't shuffled while on the same form.
  $questions = isset($form_state['storage']['questions']) ? $form_state['storage']['questions'] : grammar_wizard_prepare_questions($node);
  $form_state['storage']['questions'] = $questions;

  // $form_state['storage'] has no specific drupal meaning, but it is
  // traditional to keep variables for multistep forms there.
  $step = empty($form_state['storage']['step']) ? 0 : $form_state['storage']['step'];
  $form_state['storage']['step'] = $step;
  $last_step = count($questions) - 1;

  $form["step_$step"] = $questions[$step];
  if (isset($form["step_$step"]['question'])) {
    if (isset($form_state['storage']['correct_answer'])) {
      // Disable the radio buttons if the question was answered.
      $form["step_$step"]['question']['#disabled'] = TRUE;
      if (!$form_state['storage']['correct_answer']) {
        // If they answered the question wrong, then mark the answer they chose.
        $answer = $form_state['storage']['values']["step_$step"]['question'];
        $alpha_answer = $form["step_$step"]['question']['#options'][$answer];
        $form["step_$step"]['question']['#options'][$answer] = '<span class="grammar-wizard-incorrect">' . $alpha_answer . '</span>';
      }
    }
    $form["step_$step"]['question']['#default_value'] = empty($form_state['values']["step_$step"]['question']) ? '' : $form_state['values']["step_$step"]['question'];
  }

  $form['view_rules'] = array(
    '#markup' => '<div id="grammar-wizard-see-rules"><h2>See The Rules Again</h2><p>You can read the rules, but you\'ll have to restart the quiz again.</p>' . l('View Rules', 'homework-helper/punctuation-practice/rules/' . $form["step_$step"]['#parent_nid'], array('attributes' => array('class' => array('button')))) . '</div>',
    '#weight' => -2, 
  );

  if ($step == $last_step) {
    $form['description'] = array(
      '#markup' => grammar_wizard_final_question_content($form_state),
      '#weight' => 0,
    );
  } 
  else {
    if ($step == 0) {
      $form['instructions'] = array(
        '#markup' => '<div id="grammar-instructions">' . $form['step_0']['#instructions'] . '</div>',
        '#weight' => -3,
      );
    }  
    
    $form['numbering'] = array(
      '#markup' => '<div id="grammar-wizard-numbering">' . ($step + 1) . ' of ' . (count($questions) - 1) . '</div>',  
      '#weight' => -1,
    );
    
    // Only show this button if no answer has been submitted or if an incorrect answer was submitted.
    if (!isset($form_state['storage']['correct_answer']) || !$form_state['storage']['correct_answer']) {
      $form['check_answer'] = array(
        '#type' => 'submit',
        '#value' => !isset($form_state['storage']['correct_answer']) ? t('Check Answer') : t('Try Again'),
        '#weight' => 1,
        '#ajax' => array(
          'wrapper' => 'wizard-form-wrapper',
          'callback' => 'grammar_wizard_multistep_form_callback',
        ),
      );
    }

    // Only show this button if an answer was submitted.
    if (isset($form_state['storage']['correct_answer'])) {
      $form['next'] = array(
        '#type' => 'submit',
        '#value' => $step == $last_step - 1 ? t('See my Results') : t('Next Question'),
        '#access' => isset($form_state['storage']['correct_answer']) ? TRUE : FALSE,
        '#weight' => 1,
        '#ajax' => array(
          'wrapper' => 'wizard-form-wrapper',
          'callback' => 'grammar_wizard_multistep_form_callback',
        ),
      );
      $form['question_result'] = array('#markup' => $form_state['storage']['question_result'], '#weight' => 1,);
    }
  }
  
  return $form;
}

/**
 * Ajax callback for grammar wizard quiz form.
 */
function grammar_wizard_multistep_form_callback($form, &$form_state) {
  // Form needs to be rebuilt because it will possibly have different content.
  $form = drupal_rebuild_form('grammar_wizard_multistep_form', $form_state);
  return $form;
}

/**
 * Submit function for grammar_wizard_multistep_form.
 *
 * In AJAX this is only submitted when the final submit button is clicked,
 * but in the non-javascript situation, it is submitted with every
 * button click.
 *
 */
function grammar_wizard_multistep_form_submit($form, &$form_state) {
  // Save away the current information.
  $current_step = 'step_' . $form_state['storage']['step'];
  if (!empty($form_state['values'][$current_step])) {
    $form_state['storage']['values'][$current_step] = $form_state['values'][$current_step];
  }

  // Determine which button was pressed.
  $button_value = $form_state['triggering_element']['#value'];

  // Increment or decrement the step as needed. Recover values if they exist.
  if (in_array($button_value, array(t('Next Question'), t('See my Results')))) {
    $form_state['storage']['step']++;
    // If values have already been entered for this step, recover them from
    // $form_state['storage'] to pre-populate them.
    $step_name = 'step_' . $form_state['storage']['step'];
    if (!empty($form_state['storage']['values'][$step_name])) {
      $form_state['values'][$step_name] = $form_state['storage']['values'][$step_name];
    }
    unset($form_state['storage']['correct_answer']);
  }
  else if (in_array($button_value, array(t('Check Answer')))) {
    grammar_wizard_check_answer($form, $form_state);
  }
  else if (in_array($button_value, array(t('Try Again')))) {
    grammar_wizard_try_again($form, $form_state);
  }

  // Otherwise, we still have work to do.
  $form_state['rebuild'] = TRUE;
}

/**
 * Prepare final step content.
 */
function grammar_wizard_final_question_content($form_state) {
  $correct = 0;
  $incorrect = 0;

  foreach($form_state['storage']['student_answers'] as $answer) {
    if ($answer == 1) {
      $correct++;
    }
    if ($answer == 0) {
      $incorrect++;
    }
  }  

  if ($incorrect == 0) {
    $output = '<div id="grammar-wizard-results"><h2>Your Results:</h2><div>Correct: ' . $correct . '</div><div>Incorrect: ' . $incorrect . '</div><h2>Congratulations!</h2></div>';
    $output .= views_embed_view('grammar_practice_trophies');
  }  
  else {
    $output .= '<div id="grammar-wizard-results"><h2>Your Results:</h2><div>Correct: ' . $correct . '</div><div>Incorrect: ' . $incorrect . '</div></div>';
  }  


  return $output;
}  

/**
 * Submit callback for answer checking button on grammar wizard quiz.
 */
function grammar_wizard_check_answer($form, &$form_state) {
  $current_step = 'step_' . $form_state['storage']['step'];
  $correct_answer = check_plain($form[$current_step]['#correct_answer']);
  $selected_answer = $form_state['input'][$current_step]['question']; 
  if ($correct_answer == $selected_answer) {
    $form_state['storage']['correct_answer'] = TRUE;
    $form_state['storage']['question_result'] = '<div id="grammar-wizard-result"><h2>You Got It!</h2><div id="grammar-wizard-rule"><h2>You Understand:</h2>' . $form[$current_step]['#rule'] . '<h3>Example:</h3><div id="grammar-wizard-example">' . $form[$current_step]['#rule_example'] . '</div></div></div>';
    $form_state['storage']['student_answers'][$current_step] = 1;
  }  
  elseif (!isset($selected_answer)) {
    drupal_set_message('Please select an answer.', 'warning');
  }
  else {
    $form_state['storage']['correct_answer'] = FALSE;
    $form_state['storage']['question_result'] = '<div id="grammar-wizard-result"><h2>Incorrect!</h2><div id="grammar-wizard-rule"><h2>Remember:</h2>' . $form[$current_step]['#rule'] . '<h3>Example:</h3><div id="grammar-wizard-example">' . $form[$current_step]['#rule_example'] . '</div></div></div>';
    $form_state['storage']['student_answers'][$current_step] = 0;
  }  
}  

/**
 * Submit callback for try again button on grammar wizard quiz.
 */
function grammar_wizard_try_again($form, &$form_state) {
  $current_step = 'step_' . $form_state['storage']['step'];

  // Clear out elements indicating that the question was answered.
  unset($form_state['storage']['correct_answer']);
  unset($form_state['storage']['question_result']);

  // Ensure that the answer is not marked as correct.
  $form_state['storage']['student_answers'][$current_step] = 0;
}

