<?php

/**
 * @file
 * Prevents direct access to Flashcards.
 */

/**
 * Implements hook_menu().
 */
function flashcard_anonymous_menu() {
  $items = array();

  $items['flashcard/%flashcard_anonymous_uuid'] = array(
    'title callback' => 'node_page_title',
    'title arguments' => array(1),
    'page callback' => 'node_page_view',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  $items['flashcard/%flashcard_anonymous_uuid/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['flashcard/%flashcard_anonymous_uuid/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'node_page_edit',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file path' => drupal_get_path('module', 'node'),
    'file' => 'node.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function flashcard_anonymous_menu_alter(&$items) {
  $items['node/%node']['access callback'] = 'flashcard_anonymous_access';
}

/**
 * Implements hook_permission().
 */
function flashcard_anonymous_permission() {
  return array(
    'view anonymous flashcards' => array(
      'title' => t('View anonymous flashcards'),
    ),
    'create public flashcards' => array(
      'title' => t('Create public flashcards'),
    ),
  );
}

/**
 * Disallow direct access to flashcards.
 */
function flashcard_anonymous_access($op, $node) {
  flog_it("flashcard_anonymous_access: node-type=".$node->type);
  
  if ($node->type == 'flashcard') {
    $account = user_load($node->uid);
    return (user_access('view anonymous flashcards') || (user_access('create public flashcards', $account)));
  } else if ($node->type == 'board_member') {
    //flog_it("calling user_access: view anonymous board member...");
    //flog_it(user_access('view anonymous board member'));
    return (user_access('view anonymous board member'));
  } else {
    return node_access($op, $node);
  }
}

/**
 * Load flashcards by their UUID.
 */
function flashcard_anonymous_uuid_load($uuid) {
  $nids = entity_get_id_by_uuid('node', array($uuid));
  return ($nid = $nids[$uuid]) ? node_load($nid) : FALSE;
}

/**
 * Set the full page variable for our custom loader argument.
 */
function flashcard_anonymous_process_node(&$variables) {
  if ($variables['type'] == 'flashcard') {
    $variables['page'] = $variables['view_mode'] == 'full' && flashcard_anonymous_is_page($variables['node']);
  }
}

/**
 * Add the node object to the page variables. It will otherwise not be added,
 * as it relies on menu_get_object() in template_preprocess_page.
 */
function flashcard_anonymous_preprocess_page(&$variables) {
  if ($node = menu_get_object('flashcard_anonymous_uuid')) {
    $variables['node'] = $node;
  }
}

/**
 * Returns whether the current page is the full page view of the passed-in flashcard.
 */
function flashcard_anonymous_is_page($node) {
  $page_node = menu_get_object('flashcard_anonymous_uuid');
  return (!empty($page_node) ? $page_node->nid == $node->nid : FALSE);
}

/**
 * Implements hook_uuid_info().
 */
function flashcard_anonymous_uuid_info() {
  return array(
    'flashcard_anonymous' => array(
      'callback' => 'flashcard_anonymous_generate_uuid',
      'title' => t('Flashcard string'),
    ),
  );
}

/**
 * Generates an 8 character hexadecimal sting.
 */
function flashcard_anonymous_generate_uuid() {
    
    while($tmp_uuid = 'tfk_'.time().'_'.sprintf('%04x%04x', mt_rand(0, 65535), mt_rand(0, 65535))){
            
            $sql = db_query('select uuid from {node} where uuid = :uuid',array('uuid'=>$tmp_uuid));
            $record = $sql->fetch();
            if(!isset($record->uuid)){
                return $tmp_uuid;
            }
        
    }
    
}



//function flashcard_anonymous_generate_uuid() {
//  return sprintf('%04x%04x', mt_rand(0, 65535), mt_rand(0, 65535));
//}