<?php

// Establishes a block for the header and footer
function new_relic_ti_block_info() {

  $blocks['new_relic_header'] = array(
    'info' => t('New Relic Header Code'),
  );
  $blocks['new_relic_footer'] = array(
    'info' => t('New Relic Footer Code'),
  );
  return $blocks;
}

// adds the proper code to each block
function new_relic_ti_block_view($delta = '') {
  $block = array();
  
  switch ($delta) {
    case 'new_relic_header':
      $block['subject'] = '';
      $block['content'] = '';
      if (extension_loaded('newrelic')) {
        $block['content'] = newrelic_get_browser_timing_header();
      }
      break;
    case 'new_relic_footer':
      $block['subject'] = '';
      $block['content'] = '';
      if (extension_loaded('newrelic')) {
        $block['content'] = newrelic_get_browser_timing_footer();
      }
      break;
  }
  return $block;
}